
# Name your project! Project names should contain only lowercase characters
name: 'dbt_aoe'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_aoe'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  dbt_aoe:
    # Config indicated by + and applies to all files
    bronze:
      +materialized: table
      +schema: bronze
    silver:
      +materialized: table
      +schema: silver
    gold:
      +materialized: table
      +schema: gold