# parse_date params (update here for 1 time loads or backdating)
backdate_days_start: 70
backdate_days_end: -1
date_format: '%Y-%m-%d'

# apis
base_url: https://aoestats.io
db_endpoint: /api/db_dumps.json

relic_base_url: https://aoe-api.worldsedgelink.com
relic_endpoint: '/community/leaderboard/getLeaderBoard2?'
relic_params: 
  leaderboard_id: 3
  title: age2
  sort_by: 0
  chunk_size: 100 
relic_file_name: rl_api/relic
relic_max_rows: 5000

# s3 bucket. Other bucket params are in .env file.
bucket: aoe2dumps