name: CI Workflow

on: 
  pull_request:
    branches:
      - main

jobs:
  lint_and_test:
    name: Lint & Format Codebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt 
      
      - name: Run_linting_with_Black
        uses: psf/black@stable
        with:
          src: '.'
          options: '--check'
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for linting errors
        if: steps.Run_linting_with_Black.outcome == 'failure'
        run: echo "Linting errors found. Please fix and re-commit."
        continue-on-error: true 

      - name: Run tests with pytest
        run: |
          pytest src/project_tests.py

  dev_dbt_deployment:
    name: Slim CI dbt-run in dev environment
    needs: lint_and_test 
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install dbt-core dbt-snowflake 
    
      - name: Write profiles.yml
        env:
          DBT_PROFILES: ${{ secrets.DBT_PROFILES }}
        run: echo "$DBT_PROFILES" > src/transform/dbt_aoe/profiles.yml

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Download manifest.json from S3
        run: |
          aws s3 cp s3://aoe2dumps/dev_artifacts/manifest.json src/transform/dbt_aoe/manifest.json

      - name: Run dbt debug
        run: |
          cd src/transform/dbt_aoe
          dbt debug

      - name: Run dbt deps
        run: |
          cd src/transform/dbt_aoe
          dbt deps

      - name: Run dbt compile
        run: |
          # This creates the current manifest for the dbt project, based on merged files
          cd src/transform/dbt_aoe
          dbt compile

      - name: Dbt list changed files
        run: |
          # This will list the changes between our current files, and what was last merged to prod
          cd src/transform/dbt_aoe
          dbt ls --models state:modified --state .

      - name: Refresh dbt external tables
        run: |
          cd src/transform/dbt_aoe
          dbt run-operation --target dev stage_external_sources --vars "ext_full_refresh: true"

      - name: Run dbt run
        run: |
          cd src/transform/dbt_aoe
          dbt run --target dev --models state:modified+ --state .

      - name: Run dbt tests
        run: |
          cd src/transform/dbt_aoe
          dbt test --target dev --models state:modified+ --state .

      - name: Upload updated manifest.json to S3
        run: |
          aws s3 cp src/transform/dbt_aoe/target/manifest.json s3://aoe2dumps/dev_artifacts/manifest.json
    