name: Lint and Format Code

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint_and_format:
    name: Lint & Format Codebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Create and activate virtual environment
        run: |
          python -m venv .venv
          source .venv/bin/activate

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install --no-binary=:all: numpy==1.22 pandas==1.4.4
          pip install --no-binary=:all: -r requirements.txt  # Install other dependencies
      
      - name: Verify NumPy version
        run: python -c "import numpy; print(numpy.__version__)"

      - name: Run_linting_with_Black
        uses: psf/black@stable
        with:
          src: '.'
          options: '--check'
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for linting errors
        if: steps.Run_linting_with_Black.outcome == 'failure'
        run: echo "Linting errors found. Please fix and re-commit."
        continue-on-error: true 

      - name: Run tests with pytest
        run: |
          pytest project/project_tests.py