name: Lint and Format Code

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint_and_format:
    name: Lint & Format Codebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt 
      
      - name: Run_linting_with_Black
        uses: psf/black@stable
        with:
          src: '.'
          options: '--check'
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for linting errors
        if: steps.Run_linting_with_Black.outcome == 'failure'
        run: echo "Linting errors found. Please fix and re-commit."
        continue-on-error: true 

      - name: Run tests with pytest
        run: |
          pytest src/project_tests.py

  dbt-run:
    name: Full dbt-run in dev environment
    needs: lint_and_format 
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install dbt-core dbt-snowflake 

      - name: Debug repository structure
        run: |
          pwd
          ls -R ${GITHUB_WORKSPACE}
     
      - name: Create profiles directory
        run: mkdir -p ${GITHUB_WORKSPACE}/.dbt

      - name: Write profiles.yml file
        working-directory: ${GITHUB_WORKSPACE}/.dbt
        env:
          DBT_PROFILES: ${{ secrets.DBT_PROFILES }}
        run: echo "$DBT_PROFILES" > profiles.yml

      - name: Run dbt debug
        working-directory: /home/runner/work/aoe_project/aoe_project/src/transform/dbt_aoe
        run: |
          dbt debug --profiles-dir=${GITHUB_WORKSPACE}/.dbt
          dbt run --target dev --profiles-dir=${GITHUB_WORKSPACE}/.dbt


